### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by wangxun0407** [onlyforhebe/zhihu-daily#1]
使用http://localhost:8080访问，一直报“XMLHttpRequest cannot load http://news-at.zhihu.com/api/4/news/latest. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.” 请问怎么解决？

**Comment by gfhejun** [comment]
这个是跨域问题导致的，可以简单通过浏览器设置解决，以下是在chrome下的处理方法：

1、关闭chrome浏览器；

2、如果你是在macOS下开发的，在命令行输入open -a /Applications/Google\ Chrome.app --args --disable-web-security --user-data-dir来打开chrome浏览器；
如果你是在windows环境开发的，具体的设置细节我忘了，可以百度一下“chrome跨域设置 disable-web-security”。

3、重新打开chrome时，如果你看到浏览器出现“您使用的是不受支持的命令行标记：—disable-web-security。稳定性和安全性会有所下降。”时即设置成功。


当然，你也可以通过配置本地的nginx来解决跨域问题，不过相对复杂一点，所以还是推荐以上方法。
